server:
  port: 3344

spring:
  application:
    name: cloud-config-center  #注册进eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yeqifu/SpringCloud-Config.git  #GitHub上面的git仓库的名字
          ####搜索目录
          search-paths:
            - SpringCloud-Config
      #####读取分支
      label: master

#服务注册到eureka上
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka